blank_issues_enabled: false
contact_links:
  - name: Create an issue
    url: https://github.com/mobxjs/mobx/issues/new/choose
    about: This repo will be archived soon. Please use this link to create an issue in mobx repo.
  - name: Documentation
    url: https://mobx.js.org
  - name: GitHub discussions
    url: https://github.com/mobxjs/mobx/discussions    
  - name: StackOverflow
    url: https://stackoverflow.com/questions/tagged/mobx
